agents:
  queue: "android"

steps:
  - label: "Publish :fluxc-annotations"
    key: "publish-fluxc-annotations"
    command: .buildkite/publish-fluxc-annotations.sh

  - label: "Publish :fluxc-processor"
    key: "publish-fluxc-processor"
    depends_on:
      - "publish-fluxc-annotations"
    command: .buildkite/publish-fluxc-processor.sh

  - label: "Publish :fluxc"
    key: "publish-fluxc"
    depends_on:
      - "publish-fluxc-processor"
      - "publish-fluxc-annotations"
    command: .buildkite/publish-fluxc.sh

  - label: "Publish :plugins:woocommerce"
    key: "publish-plugins-woocommerce"
    depends_on:
      - "publish-fluxc-processor"
      - "publish-fluxc-annotations"
      - "publish-fluxc"
    command: .buildkite/publish-plugins-woocommerce.sh
